export let data = [
    {
    //Chapter 1
      atmosphere:"n.大气层，大气圈；气氛",
      hydrosphere:"n.水圈；大气中的水汽",
      lithosphere:"n.岩石圈",
      oxygen:"n.氧气",
      oxide:"n.氧化物",
      carbon_dioxide: "n.二氧化碳",
      hydrogen:"氢气",
      core:"n.中心，核心；地核",
      crust:"n.地壳；外壳",
      mantle:"n.地幔，斗篷，披风；v.覆盖",
      longitude: "n.经度",
      latitude: "n.纬度",
      horizon: "n.地平线；眼界，见识",
      altitude: "n.高度，海拔",
      disaster: "n.灾难",
      mishap:"n.小灾难",
      catastrophic: "adj.灾难性的",
      calamity: "n.灾难，不幸的事",
      endanger: "v.使遭受危险，危及",
      jeopardise:'v.危害，危及',
      destructive:'adj.破坏性的，有害的',
      greenhouse:'n.温室，暖房',
      phenomenon: 'n.现象',
      pebble: 'n.鹅卵石',
      magnet:'n.磁铁，吸铁石',
      ore: 'n.矿石；矿',
      mineral:'n.矿物，矿物质；矿产',
      marble:'n.大理石；（玩具）弹球',
      quartz: 'n.石英',
      granite: 'n.花岗岩',
      gust: 'n.一阵狂风；（感情的）迸发',
      breeze: 'n.微风，和风',
      monsoon: 'n.季风；雨季',
      gale: 'n.大风',
      hurricane:'n.飓风，暴风',
      tornado:'n.龙卷风',
      typhoon: 'n.台风',
      volcano: 'n.火山',
      erupt: 'v.爆发，喷发；（斑疹等）突然出现',
      magma: 'n.岩浆',
      thermodynamic:'adj.热力的；热力学的',
      smog: 'n.烟雾，雾霾',
      fume: 'n.(难闻且常为有害的）烟，气体 v.冒烟；发怒',
      mist: 'n.薄雾；水汽；使视线模糊的东西',
      tsunami: 'n.海啸',
      drought: 'n.干旱，旱灾',
      flooding: 'n.洪水泛滥',
      torrent: 'n.激流，洪流',
      earthquake: 'n.地震',
      seismic: 'adj.地震的，地震引起的',
      avalanche: 'n.雪崩',
      terrain: 'n.地形',
      landscape:'n.风景，地貌；v.对......进行景观美化',
      continent: 'n.大陆；洲',
      cave: 'n.洞穴，山洞',
      cliff:'n.悬崖，峭壁',
      glacier:'n.冰河，冰川',
      swamp:'n.沼泽，湿地',
      delta:'n.三角洲',
      plain:'n.平原 adj.简朴的，明白的',
      plateau:'n.高原',
      oasis:'n.绿洲；宜人之地',
      globe: 'n.球体；地球仪 【the~】地球',
      hemisphere: 'n.半球',
      equator:'n.赤道',
      arctic: 'adj.极冷的；n.【the~】北极地区，北极',
      Antarctic:'adj.南极的；n.【the~】南极地区，南极洲',
      pole:'n.(地)极；截然相反的两极之一',
      polar: 'adj.极地的，近极地的；对立的',
      axis: 'n.轴，轴线',
      deteriorate:'v.恶化，变坏',
      aggravate:'v.加剧，加重，使恶化',
      degrade:'v.降解；降低......的身份；使恶化，使退化',
      upgrade:'v.使升级；提高，改善',
      erode:'v.腐蚀，侵蚀',
      Mediterranean: 'adj.地中海的；地中海地区的；n.地中海；地中海地区',
      Atlantic:'adj.大西洋；n.【the~】大西洋',
      pacific:'adj.平静的，和平的；太平洋的；n.【the~】太平洋',
      ocean:'n.海洋；（五大洋之一的）洋',
      marine:'adj.海生的，海洋的，海事的；n.水兵',
      navigation:'n.航行；航海',
      gulf:'n.海湾',
      beach:'n.海滩，河滩',
      coast:'n.海岸，海滨',
      shore:'n.(海，湖等大水域的）岸，滨',
      tide:'n.趋势,潮流；潮汐',
      current: 'n.水流，潮流；电流；气流',
      brook:'n.小河，溪',
      stream:'n.小河，溪，流；v.流动，流出',
      shallow:'adj.浅的;肤浅的，浅薄的',
      superficial:'adj.表皮的，表层的',
      flat:'adj.平坦的；扁平的；单调的',
      smooth:'adj.光滑的；平稳的；流畅的',
      rough:'adj.粗糙的；粗略的',
      sandy:'adj.铺满沙的；含沙的',
      stony:'adj.石头的；多石的',
      vertical:'adj.垂直的，直立的',
      steep:'adj.陡峭的，陡直的',
      parallel:'n.平行线；相似之物；相似之处；adj.平行的；v.与......相似；比得上',
      narrow:'adj.狭窄的；有局限的 n.海峡 v.变窄',
      Oceania:'n.大洋洲',
      mainland:'n.大陆，本土',
      peninsula:'n.半岛',
      climate:'n.气候；风气，思潮，环境',
      weather:'n.天气，气象',
      meteorology:'n.气象学',
      mild:'adj.温和的；不严重的',
      heating:'n.供暖；暖气装置',
      moderate:'adj.适度的；温和的；中等的;v.使缓和',
      warm:'adj.温暖的;v.使变暖',
      thermal:'adj.热量的',
      tropics:'n.【the~】热带地区',
      arid:'adj.干燥的，干旱的；枯燥的',
      moist:'adj.潮湿的，湿润的',
      damp:'adj.潮湿的，湿气重的',
      humid:'adj.潮湿的，湿热的',
      snowy:'adj.下雪多的，被雪覆盖的',
      frost:'n.霜；霜冻；严寒',
      hail:'n.雹，冰雹 v.赞扬；招呼；下雹',
      thaw:'v.解冻，融解，融化;n.解冻时期',
      chill:'v.使变冷；使恐惧；n.寒冷；害怕',
      freeze:'v.结冰 n.霜冻；严寒期',
      frigid:'adj.寒冷的',
      tremble:'v./n.颤栗，颤抖',
      shiver:'v.颤抖，哆嗦，发抖',
      thunder:'n.雷；雷声；v.打雷；轰隆隆快速的移动',
      lighting:'n.闪电；adj.闪电般的，极快的',
      stormy:'adj.有暴风雨的；争吵激烈的；（大海）波涛汹涌的',
      downpour:'n.倾盆大雨',
      rainfall:'n.降雨量',
      sprinkle:'v.撒，洒；下小雨；n.少量；小雨',
      rainbow:'n.虹；彩虹',
      shower:'n.阵雨；（一）阵；淋浴',
      Celsius:'adj.摄氏度的；n.摄氏温度',
      temperature:'n.气温；体温；温度',
      forecast:'n.预测，预报；v.预言，预测',
      peak:'n.山峰；顶点；v.达到最大值',
      mount:'v.渐渐增加；爬上，登上 n.山',
      mountain:'n.山，山岳，高山',
      range:'n.山脉；范围',
      ridge:'n.山脊，山脉；使隆起',
      slope:'v.倾斜；有坡度；n.山坡；斜坡',
      valley:'n.山谷，溪谷',
      hillside:'n.（小山的）山腰，山坡',
      overlook:'v.俯瞰，远眺；未注意到',
      southeast:'n.东南方；东南部；adj.东南方的；东南部的',
      southwest:'n.西南方；西南部；adj.西南方的；西南部的',
      northeast:'n.东北方；东北部；adj.东北方的；东北部的',
      northwest:'n.西北方；西北部；adj.西北方的；西北部的',
      eastern:'adj.东部的；东方的',
      oriental:'adj.东方的（尤指中国的和日本的）',
      inevitable:'adj.不可避免的，必然的',
      irreversible:'adj.不可逆转的；不可挽回的',
      irregularly:'adv.不规则地；不合常规地',
      inappropriate:'adj.不合适的',
      abnormal:'adj.不正常的，反常的；变态的',
      sediment:'n.沉淀物；沉积物',
      silt:'n.淤泥，泥沙；v.使淤塞',
      muddy:'adj.泥泞的；浑浊的',
      clay:'n.黏土，陶土',
      dirt:'n.污垢，灰尘；泥土',
      rural:'adj.农村的，乡村的；田园的',
      suburb:'n.郊区，郊外，近郊',
      outskirts:'n.郊区，市郊',
      remote:'adj.遥远的；偏远的；疏远的',
      desolate:'adj.荒凉的',
      distant:'adj.疏远的；遥远的',
      adjacent:'adj.邻近的；毗连的',
      toxic:'adj.有毒的',
      pollution:'n.污染',
      pollutant:'n.污染物质',
      contaminate:'v.弄脏，污染',
      geology:'n.地质学；地质状况',
      border:'n.边界；边界地区；镶边；v.和......毗邻；形成......的边界',
      margin:'n.边缘；页边空白；余地',
      fringe:'n.边缘；刘海儿 adj.次要的；非主流的',
      plate:'n.(地质学中的大陆)板块；盘',
      debris:'n.碎片，残骸',
      crack:'v.破裂；发出破裂声；n.裂缝；缝隙',
      gap:'n.缺口，裂缝；差距；空白',
      splendid:'adj.极好的；壮观的',
      grand:'adj.宏大的；豪华的；宏伟的，极好的',
      magnificent:'adj.壮丽的，宏伟的；令人印象深刻的',
      super:'adj.超级的,极好的',
      interesting:'adj.有趣的；引入入胜的',
      dramatic:'adj.戏剧的；引入注目的',
      wilderness:'n.荒野',
      deforest:'v.毁掉......的森林',
      barren:'adj.贫瘠的，荒芜的；不结果实的',
      fertile:'adj.肥沃的，富饶的',
      fertilise:'v.施肥于',
      solar:'adj.太阳的，日光的',
      lunar:'adj.月亮的，月球的',
      calendar:'n.日历;历法',
      sunrise:'n.日出',
      sunset:'n.日落',
      eclipse:'n.日食；月食',
      dusk:'n.黄昏，傍晚',
      heaven:'n.天堂；极乐（之地）',
      paradise:'n.天堂；乐园，福地',
      sunshine:'n.阳光，日光',
      shade:'n.阴影部分；背阴处；v.给......遮挡（光线）',
      shadow:'n.影子，阴影',
      vapour:'n.蒸气；水汽',
      evaporate:'v.使蒸发；消失',
      circulate:'v.使循环，使流通；（信息等）传播',
      preciptate:'v.(水汽等)凝结；沉淀',
      reservior:'n.水库，蓄水池',
      waterfall:'n.瀑布',
      fountain:'n.喷泉；源泉',
      spring:'n.春天；泉水',
      dew:'n.露水',
      pour:'v.倾泄；倒；（雨）倾盆而下',
      drain:'v.排空；使流出；n.耗竭',
      drip:'v.滴出（液体）;滴下',
      drown:'v.使淹死；浸泡',
      blow:'v.吹；（风）吹；吹动；n.用力的一击；打击，挫折',
      puff:'v.喷出；喘息；n.（吹出的）一股，一缕',
      gush:'v.n./ 涌出',
      dense:'adj.密集的；稠密的',
      intensity:'n.强度；强烈',
      intensive:'adj.加强的，集中的，密集的',
      emerge:'v.浮现，露出；摆脱出来；暴露',
      flash:'v.使闪光；使闪现；（通过计算机，卫星等）快速发送；n.闪光（灯）;闪现',
      float:'v.漂浮；飘浮',
      environment:'n.自然环境；环境，周围情况',
      surrounding:'adj.周围的，附近的',
      condition:'n.条件；情况，状态',
      situation:'n.情况，处境，形势',
      nature:'n.大自然；本性；性质',
      natural:'adj.自然的；天然的',
      artificial:'adj.人造的',
      synthetic:'adj.人造的，合成的；n.合成物',
      petrol:'n.【英】汽油',
      gas:'n.气体;【美】汽油',
      gasoline:'n.【美】汽油',
      petroleum:'n.石油'
    },
    {
      //Chapter 2
      photosynthesis:'n.光合作用',
      respire:'v.呼吸',
      dioxide:'n.二氧化物',
      vegetation:'n.草木，植物',
      herb:'n.药草；香草',
      perennial:'n.多年生植物 adj.长期的，持久的',
      botany:'n.植物学',
      ecology:'n.生态学；生态',
      ecosystem:'n.生态系统',
      eco_friendly:'adj.对生态环境友好的，不妨害生态环境的',
      horticulture:'n.园艺学；园艺',
      organism:'n.有机体，生物',
      genetics:'n.遗传学',
      mutation:'n.突变，变异',
      variation:'n.变种，变异',
      diversity:'n.多样性',
      hybridisation:'n.杂交',
      classify:'v.分类',
      reproduce:'v.繁殖',
      evolve:'v.进化；使发展，使逐步形成',
      fluctuate:'v.波动，起伏',
      reclaim:'v.开垦，开拓，利用',
      cultivate:'v.耕作；培养',
      snow:'v.播种',
      harvest:'v.收割；n.收获；收成',
      pluck:'v.采，摘',
      pick:'v.拾，摘',
      yield:'v.出产；屈服，服从；n.产量；投资收益',
      rear:'v.培养，抚养；饲养；n.后部',
      arable:'adj.适于耕种的',
      plough:'n.犁；v.耕',
      spade:'n.铲',
      rake:'n.粑子；v.粑；搜索',
      stack:"n. 堆，跺；v.堆积",
      heap:'n.（大而杂乱的）堆',
      bundle:'n.捆，包，束',
      bunch:'n.一束（花）,一串（钥匙）',
      vase:'n.瓶，花瓶',
      sunlight:'n.阳光',
      short_day:'adj.短日照的',
      shade_tolerant:'adj.耐阴的',
      fungus:'n.真菌',
      mould:'n.霉菌；v.发霉',
      pollen:'n.花粉；v.给......授粉',
      germinate:'v.使发芽；开始生长',
      seed:'n.种子，籽；萌芽',
      burgeon:'n.嫩枝，新芽；v.急速增长；发芽，抽枝',
      bud:'n.芽，苞，蓓蕾',
      flower:'v.开花；n.花朵',
      blossom:'v.开花；n.花朵',
      bloom:'n.花朵',
      scent:'n.气味；香味；v.使具有香味',
      aromatic:'adj.芳香的',
      ripen:'v.使成熟',
      fruit:'v.结果实',
      wither:'v.使枯萎',
      decompose:'v.使分解；使腐烂',
      rot:'v.使分解，使腐坏；n.腐烂',
      decay:'v.腐烂',
      stale:'adj.不新鲜的；没有新意的，陈腐的',
      rainforest:'n.雨林',
      jungle:'n.（热带）丛林，密林',
      plantation:'n.种植园；栽植',
      field:'n.原野；场地；野外',
      terrace:'n.梯田',
      timber:'n.木材，木料；林木',
      charcoal:'n.木炭',
      log:'n.原木；日志',
      logo:'n.标识，标志，微标',
      forestry:'n.林学；林业',
      branch:'n.树枝；分支机构，分店',
      trunk:'n.树干；躯干；大箱子',
      bough:'n.大树枝',
      root:'n.根；v.使生根',
      hay:'n.干草',
      straw:'n.稻草，麦秆；吸管',
      reed:'n.芦苇',
      thorn:'n.刺，棘刺；荆棘',
      weed:'n.杂草，野草；v.除杂草',
      grass:'n.草；草地',
      meadow:'n.草地；牧场',
      lawn:'n.草地，草坪',
      olive:'n.橄榄；橄榄树',
      pine:'n.松树；松木',
      vine:'n.葡萄藤',
      violet:'n.堇菜',
      tulip:'n.郁金香',
      mint:'n.薄荷；薄荷糖；铸币厂；v.铸造（硬币）',
      reef:'n.(暗)礁，礁脉',
      alga:'n.海藻，藻',
      enzyme:'n.酶',
      catalyst:'n.催化剂；促进因素',
      release:'v./n.释放；发布',
      emission:'n.排放，散发；排放物，散发物',
      absorb:'v.吸收；吸引全部注意力',
      circulation:'n.流通；循环；流转',
      exceed:'v.超过',
      uptake:'n.摄取；领会',
      nutrient:'n.营养物质',
      energy:'n.能源；精力',
      surroundings:'n.环境',
      mechanism:'n.机制；构造',
      counterbalance:'n.起平衡作用的事物；抗衡力',
      protect:'v.保护',
      preserve:'v.保护；维持（原状）；保存',
      conservation:'n.(对自然环境的)保护；保存',
      bush_fire:'n.林区大火',
      extinguish:'v.扑灭（火）；使想法，感情等破灭',
      destruct:'v.使自毁',
      ruin:'v.毁坏，摧毁；n.毁灭；废墟',
      perish:'v.毁灭，消亡；腐烂',
      demolish:'v.拆除；毁坏，破坏；推翻',
      infringe:'v.侵犯；违反',
      undermine:'v.破坏；逐渐削弱',
      extinction:'n.灭绝',
      pattern:'n.模式；式样；底样',
      outcome:'n.结果',
      impact:'n.影响',
      seasonal:'adj.季节性的',
      experimental:'adj.实验的；试验性的',
      favourable:'adj.有利的；赞成的，肯定的',
      productive:'adj.多产的',
      effective:'adj.有效的',
      efficient:'adj.效率高的',
      considerable:'adj.相当多的',
      massive:'adj.巨大的，大规模的；庞大的',
      immense:'adj.巨大的',
      maximal:'adj.最大的',
      minimal:'adj.最小的，极小的',
      optimal:'adj.最佳的，最理想的'
    }
  ]