export let data= [
    {
        index: 1,
        title:'It is argued that getting married before finishing school or getting a job is foolish. To what extent do you agree or disagree? ',
        titleDescription:'有人认为，在完成学业或找到工作之前结婚是愚蠢的。 你在多大程度上同意或不同意? ',
        one: 'There is an ongoing debate on the timing of getting married. Some people claim that getting married before being financially independent is not a good idea, whereas some disagree. Personally speaking, I strongly agree that getting married before finishing school or getting a job is foolish. ',
        oneDespection:'关于结婚的时间问题，目前仍有争论。有些人声称在经济独立之前结婚不是一个好主意，而有些人则不同意。就我个人而言，我强烈同意在完成学业或找工作之前结婚是愚蠢的。',
        two: 'The first and the most important reason for my belief is that getting married before completing school or getting a job can cause a financial burden because couples do not have enough income to support their life. To be more specific, various aspects of life incur costs for married couples when supporting a family, such as buying a house or purchasing a vehicle. This can be established by a recent study by Oxford University, which stated that 71.3% of the couples who got married before finishing school or getting a job ended up with divorce as they do not have enough income to support their living costs.',
        twoDespection:'我相信的第一个也是最重要的原因是，在完成学业或找到工作之前结婚可能会造成经济负担，因为夫妻没有足够的收入来维持他们的生活。更具体地说，已婚夫妇在养家时，生活的各个方面都会产生成本，比如买房或买车。牛津大学最近的一项研究证实了这一点，该研究表明，71.3%在完成学业或找到工作之前结婚的夫妇最终离婚，因为他们没有足够的收入来支付生活费用。',
        three:'On the other hand, the second reason for this argument is that getting married before finishing school or getting a job can limit people_s social networks, which is harmful to their future career development. To illustrate, those who are married must spend more time on family affairs than socializing with people from schools or the professional field, which deprives them of opportunities to obtain new information that is conducive to the development of their study or career. According to the annual report of the Australian government, more than 70% of the citizens stated that getting married before finishing their education or getting a job could influence their social networks negatively.',
        threeDespection:'另一方面，这种说法的第二个原因是，在完成学业或找到工作之前结婚会限制人们的社交网络，这对他们未来的职业发展有害。举例来说，那些已婚的人必须花更多的时间在家庭事务上，而不是与学校或专业领域的人社交，这剥夺了他们获得有利于他们学习或职业发展的新信息的机会。根据澳大利亚政府的年度报告，超过70%的公民表示，在完成教育或找到工作之前结婚可能会对他们的社交网络产生负面影响。',
        four:'With all the points above, the conclusion can be made that getting married before completing study or getting a job is irrational due to the creation of financial burden and limitation of people_s social networks.',
        fourDespection:'综上所述，可以得出这样的结论：由于经济负担的产生和人们社交网络的限制，在完成学业或找到工作之前结婚是不合理的。'
    },
    {
        index: 2,
        title:'Some people think human behaviors can be changed by laws, while others think laws have little effect. What is your opinion.',
        titleDescription:'一些人认为法律可以改变人的行为，另一些人认为法律没有什么作用。你的意见是什么? ',
        one: 'Laws are important to current society because they distinguish between right and wrong. Some people think human behaviors can be changed by laws, whereas others think laws have little effect. Personally speaking, I strongly believe that laws can change human behaviors. ',
        oneDespection:'法律对当今社会很重要，因为它们区分是非。有些人认为法律可以改变人类的行为，而另一些人则认为法律几乎没有作用。就我个人而言，我坚信法律可以改变人类的行为。',
        two: 'The first and the most important reason for my belief is that laws can change human behaviors because people are constrained by the punishment brought by laws. To be specific, people are aware that there will be consequences and punishment that comes from law enforcement for any illegal activities, so people tend to control their desire from criminal behaviors. This can be established by a recent study by Oxford University, which stated that the crime rate has dropped by 89% under the influence of law.',
        twoDespection:'我相信的第一个也是最重要的原因是，法律可以改变人类的行为，因为人们受到法律带来的惩罚的约束。具体来说，人们意识到任何非法活动都会受到执法的后果和惩罚，因此人们倾向于从犯罪行为中控制自己的欲望。牛津大学最近的一项研究证实了这一点，该研究表明，在法律的影响下，犯罪率下降了89%。',
        three:'On the other hand, the second reason for this argument is that laws provide general guidance for people. To illustrate, laws give people correct instructions when people are facing an ethical dilemma or moral hazard. Besides, laws teach individuals how to deal with complex issues and introduce a border between right and wrong, which can prevent people from doing unethical things. According to the annual report of the Australian government, more than 70% of the citizens stated that laws ensure people do the right things.',
        threeDespection:'另一方面，这一论点的第二个原因是法律为人们提供了一般性的指导。举例来说，当人们面临道德困境或道德风险时，法律会给人们正确的指示。此外，法律教会个人如何处理复杂的问题，并引入是非界限，这可以防止人们做不道德的事情。根据澳大利亚政府的年度报告，超过70%的公民表示，法律确保人们做正确的事情。',
        four:'With all the points above, the conclusion can be made that laws can change human behaviors because it is a restrictive approach to prevent crimes and provides general guidance for individuals.',
        fourDespection:'综上所述，可以得出这样的结论：法律可以改变人类行为，因为它是预防犯罪的一种限制性方法，并为个人提供了一般性指导。'
    },
    {
        index: 3,
        title:'In some companies, some employers involve employees in the decision-making process of products and services. What are the advantages and disadvantages of such a policy?',
        titleDescription:'有些雇主会让员工参与产品和服务的决策过程。这种政策的优点和缺点是什么?',
        one: 'In some companies, employers let employees be involved in the decision-making process of products and services. Personally speaking, this management method has both advantages and disadvantages.',
        oneDespection:'在一些公司，雇主让员工参与产品和服务的决策过程。就我个人而言，这种管理方法既有优点也有缺点。',
        two: 'The key benefit of letting employees attend a decision-making meeting is that it can increase employees’ working performance. To be more specific, when employees are involved in companies’ decision-making processes, they will feel respected and improve their enthusiasm for work. For example, a recent report from the Microsoft Company can further support my idea, which mentions when employees get involved in decision-making meetings for a new wifi adaptor, their working performance increased at least 89%.',
        twoDespection:'让员工参加决策会议的主要好处是可以提高员工的工作绩效。更具体地说，当员工参与公司的决策过程时，他们会感到受到尊重，并提高他们的工作热情。例如，微软公司最近的一份报告可以进一步支持我的想法，该报告提到，当员工参加新wifi适配器的决策会议时，他们的工作表现至少提高了89%。',
        three:'The main downside of involving some employees in the decision-making process about their products and services is that such a method would decrease the working efficiency of companies. To be more specific, employees involved in the decision-making process need to follow several complex procedures under the regulatory framework of companies, and it consumes too much time, which will reduce the efficiency of companies. To further support my statement, an article published in China Daily revealed that 50% of employers believed that employees participating in the decision-making process might decrease the working efficiency of companies.',
        threeDespection:'让一些员工参与其产品和服务的决策过程的主要缺点是，这种方法会降低公司的工作效率。更具体地说，在公司的监管框架下，参与决策过程的员工需要遵循几个复杂的程序，而且这消耗了太多的时间，这将降低公司的效率。为了进一步支持我的说法，《中国日报》上发表的一篇文章透露，50%的雇主认为员工参与决策过程可能会降低公司的工作效率。',
        four:'With all the points above, engaging employees in the decision-making process brings both benefits and problems. Therefore, companies should weigh the advantages against the disadvantages before determining the strategy.',
        fourDespection:'有了以上所有要点，让员工参与决策过程既带来好处，也带来问题。因此，在确定战略之前，公司应该权衡利弊。'
    },
    {
        index: 4,
        title:'The formal written examination can be a valid method to assess students’ learning. To what extent do you agree or disagree? ',
        titleDescription:'正式的笔试是评估学生学习成绩的有效方法。你在多大程度上同意或不同意?',
        one: 'There is no doubt that the formal written examination has been a conventional way to evaluate students’ performance. Some people argue that this is the best way for assessment in schools, whereas others believe that more innovative methods should replace written exams. Personally speaking, the formal written examination is a valid method to assess students’ learning process, which can be supported as follows.',
        oneDespection:'毫无疑问，正式的笔试已经成为评估学生成绩的一种常规方式。一些人认为这是学校评估的最佳方式，而另一些人则认为更具创新性的方法应该取代笔试。就我个人而言，正式笔试是评估学生学习过程的有效方法，可以支持如下。',
        two: 'The first and the most important reason for my belief is that the formal written examination can be a valid method to assess students’ learning because it can estimate whether they have a solid foundation of the subjects they learned in this term or not. To be specific, the formal written exam is an integrated test, which can test how deep the students master the knowledge, and it can reflect the student learning results through academic marks. To take my own experience as an example, I gained a low score in one subject, which means I did not grasp the knowledge well.',
        twoDespection:'我相信的第一个也是最重要的原因是，正式的笔试可以成为评估学生学习情况的有效方法，因为它可以评估他们是否对本学期所学的科目有坚实的基础。具体来说，正式笔试是一种综合测试，它可以测试学生对知识的掌握程度，它可以通过学业成绩来反映学生的学习成绩。以我自己的经历为例，我在一门课上得了低分，这意味着我没有很好地掌握知识。',
        three:'On the other hand, the second reason for this argument is that the formal exam can assess how much time students spend on reviewing their courses. To illustrate, if students spend enough time on each subject and have a deep understanding of it, they will get good scores on the formal exam. This can be established by a recent study by Oxford University, which stated that over 76% of the students who spend sufficient time studying can gain good academic performance from the exams, which means the formal written exam is a valid method.',
        threeDespection:'另一方面，这种说法的第二个原因是，正式考试可以评估学生花在复习课程上的时间。举例来说，如果学生在每门科目上花足够的时间并深入了解，他们就会在正式考试中取得好成绩。牛津大学最近的一项研究证实了这一点，该研究表明，花足够时间学习的学生中，超过76%的人可以从考试中获得良好的学习成绩，这意味着正式笔试是一种有效的方法。',
        four:'With all the points above, the conclusion can be drawn that formal written examination is a valid method because it can directly evaluate students’ performance. In this regard, schools should promote the use of such exams.',
        fourDespection:'综合以上几点，可以得出这样的结论：正式笔试是一种有效的方法，因为它可以直接评估学生的成绩。在这方面，学校应该提倡使用这种考试。'
    },
    {
        index: 5,
        title:'It is often argued that studying overseas is overrated. There are many scholars who study locally. Is travel a necessary component of quality education?',
        titleDescription:'人们常常认为海外留学被高估了。有许多学者在当地学习。旅行是素质教育的必要组成部分吗?',
        one: 'Some people believe that studying overseas is overrated, and there is no value to travel overseas for better education, whereas others have opposite opinions. Personally speaking, I believe that it is necessary to study abroad for a better education.',
        oneDespection:'一些人认为出国留学被高估了，为了更好的教育而出国旅行没有价值，而另一些人则持相反意见。就我个人而言，我认为为了更好的教育而出国留学是必要的。',
        two: 'The first and most important reason for my belief is that studying abroad can enhance students’ learning ability. To be specific, traveling overseas for education can be a challenge for students because of the language and cultural barriers, which drive them to study harder. In this case, students are pushed to improve their learning ability to better outperform their peers. For example, an investigation conducted by Melbourne University shows that 80% of students who are studying overseas claimed they had enhanced their learning ability.',
        twoDespection:'我相信出国留学能提高学生的学习能力，这是第一个也是最重要的原因。具体来说，出国留学对学生来说可能是一个挑战，因为语言和文化障碍驱使他们更加努力地学习。在这种情况下，学生们被要求提高学习能力，以更好地超越同龄人。例如，墨尔本大学的一项调查显示，80%的海外留学生声称他们的学习能力有所提高。',
        three:'On the other hand, the second reason for this argument is that students can benefit from better language learning when they study abroad. To illustrate, traveling overseas to pursue their academic goals provides a multitude of opportunities to speak with foreigners who are experts in their language, so this offers students a great immersive language learning experience, which can equip them with more skills and vocabulary of the foreign language. According to the annual report of the Australian government, more than 70% of the international students believe that they have achieved great progress in English Learning since they arrived in Australia.',
        threeDespection:'另一方面，这一论点的第二个原因是，学生在国外学习时可以从更好的语言学习中受益。举例来说，为了追求自己的学术目标而出国旅行提供了大量与精通外语的外国人交谈的机会，因此这为学生提供了一种身临其境的语言学习体验，使他们掌握更多的外语技能和词汇。根据澳大利亚政府的年度报告，超过70%的国际学生认为，自抵达澳大利亚以来，他们在英语学习方面取得了巨大进步。',
        four:'With all the points above, the conclusion can be drawn that it is necessary to study abroad because this education opportunity can improve students’ learning ability and help them master a foreign language.',
        fourDespection:'综合以上几点，可以得出结论：出国留学是必要的，因为这种教育机会可以提高学生的学习能力，帮助他们掌握一门外语。'
    },
    {
        index: 6,
        title:'The disadvantages of tourism in less developed countries are as great as the advantages. What is your opinion?',
        titleDescription:'旅游业在欠发达国家的缺点和优点一样大。你的意见是什么?',
        one: 'Recent years have witnessed a significant increase in tourism in less developed countries, which has brought a heated debate about the advantages and disadvantages of this trend. Views on this issue vary from person to person. From my perspective, the disadvantages of tourism in less developed countries are as great as the advantages.',
        oneDespection:'近年来，欠发达国家的旅游业显著增长，这引发了关于这一趋势的利弊的激烈辩论。对这个问题的看法因人而异。在我看来，欠发达国家旅游业的劣势和优势一样大。',
        two: 'First and foremost, the key benefit of tourism in developing countries is that it can boost the local economy, which is obvious because the influx of tourists can provide many employment opportunities to the local job market and promote local businesses including restaurants and hotels, which in turn boosts the local economy. This can be established by a recent study by Oxford University, which stated that tourism is the primary source of income in Cambodia, which increases the local GDP by 60%.',
        twoDespection:'首先，发展中国家旅游业的主要好处是它可以促进当地经济，这是显而易见的，因为游客的涌入可以为当地就业市场提供许多就业机会，并促进包括餐馆和酒店在内的当地企业，这反过来又促进了当地经济。牛津大学最近的一项研究证实了这一点，该研究指出，旅游业是柬埔寨的主要收入来源，使当地GDP增长了60%。',
        three:'On the other hand, the disadvantage of tourism in less developed countries is that the development of tourism has detrimental impacts on the local environment. To illustrate, tourism often comes with garbage pollution and improper human activities which cause damage to the natural environment. However, less developed countries have less capacity to handle these environmental challenges, which can lead to exacerbated greenhouse effects and land pollution. According to the annual report of the Australian government, more than 70% of the citizens believe that tourism is responsible for more than 60% of environmental deterioration in less developed countries.',
        threeDespection:'另一方面，欠发达国家旅游业的不利之处在于，旅游业的发展对当地环境产生了不利影响。举例来说，旅游业经常伴随着垃圾污染和不当的人类活动，对自然环境造成破坏。然而，欠发达国家应对这些环境挑战的能力较弱，这可能导致温室效应和土地污染加剧。根据澳大利亚政府的年度报告，超过70%的公民认为旅游业对欠发达国家60%以上的环境恶化负有责任。',
        four:'To summarize, although it is hard to arrive at an absolute conclusion on this complicated issue, I am still fully convinced that the advantages of tourism in less developed countries are as great as the disadvantages.',
        fourDespection:'总之，尽管在这个复杂的问题上很难得出绝对的结论，但我仍然完全相信，欠发达国家的旅游业的优势和劣势一样大。'
    },
    {
        index: 7,
        title:'In your opinion, what are the advantages and disadvantages of extreme or adventure sports? ',
        titleDescription:'在你看来，极限或冒险运动的优点和缺点是什么??',
        one: 'There is no doubt that there is an open debate on the advantages and disadvantages of extreme or adventure sports. Some people point out that extreme sports may involve a high degree of risk, whereas others think that it brings a lot of advantages. Personally speaking, I strongly believe that extreme or adventure sports have both advantages and disadvantages, which can be supported by the reasons as follows.',
        oneDespection:'毫无疑问，关于极限运动或冒险运动的优点和缺点，存在着公开的争论。一些人指出极限运动可能涉及高度风险，而另一些人则认为它带来了很多好处。就我个人而言，我坚信极限运动或冒险运动既有优点也有缺点，这可以由以下原因来支持。',
        two: 'The first and the most important reason for my belief is that extreme sports are advantageous because they can make people’s life rich and fascinating. To be more specific, people who enjoy extreme sports activities can expand their social circles and create many unforgettable moments as they push their limits to broaden their horizons. To further support the above statement, I have read an article published by The Age that 73% of people stated that extreme sports help them in having a more vibrant and more unique life experience.',
        twoDespection:'我相信极限运动的第一个也是最重要的原因是，极限运动是有利的，因为它们可以让人们的生活丰富多彩。更具体地说，喜欢极限运动的人可以扩大他们的社交圈，创造许多难忘的时刻，因为他们会突破极限，开阔视野。为了进一步支持上述说法，我阅读了《时代》杂志发表的一篇文章，73%的人表示极限运动有助于他们获得更具活力和独特的生活体验。',
        three:'On the other hand, extreme sports also bring risks as people may experience severe injuries and trauma while participating in such activities. To be more specific, extreme or adventure sports, such as skiing and snowboarding, can expose people to the risk of encountering an avalanche and may cause injuries or even a loss of life. This can be established by recent research by the University of Melbourne that 84% of skiing accidents caused people to death in 2018.',
        threeDespection:'另一方面，极限运动也带来风险，因为人们在参加此类活动时可能会受到严重伤害和创伤。更具体地说，极限或冒险运动，如滑雪和单板滑雪，会使人们面临遭遇雪崩的风险，并可能造成伤害甚至生命损失。墨尔本大学最近的研究表明，2018年84%的滑雪事故导致人员死亡。',
        four:'With all the points above, the conclusion can be made that extreme or adventure sports can enrich participants’ experiences, but it may also put people at risk of getting injured. In this regard, it is important that governments should devote sufficient funding, and public awareness should be raised to improve this situation.',
        fourDespection:'综上所述，可以得出结论，极限或冒险运动可以丰富参与者的体验，但也可能使人们面临受伤的风险。在这方面，重要的是，政府应投入足够的资金，并应提高公众意识以改善这种情况。'
    },
    {
        index: 8,
        title:'“The information revolution by modern mass communication has both positive and negative consequences for individuals and for society.” To what extent do you agree? Explain with your own experience. ',
        titleDescription:'“现代大众传播带来的信息革命对个人和社会都有积极和消极的影响。”你在多大程度上同意? 用你自己的经历来解释。',
        one: 'Nowadays, the information revolution led by modern mass media has become a prevalent topic for debate. Some people point out that they have positive consequences for both individuals and society, while others indicate that they are harmful. Personally speaking, I totally agree that the information revolution leading by modern mass media has both positive and negative effects on individuals and society.',
        oneDespection:'当今，以现代大众传媒为主导的信息革命已成为一个热门话题。一些人指出它们对个人和社会都有积极的影响，而另一些人则表示它们是有害的。就我个人而言，我完全同意以现代大众媒体为主导的信息革命对个人和社会都有积极和消极的影响。',
        two: 'On the one hand, the information revolution led by mass media can help individuals to get timely information. To be more specific, modern mass media such as computers can allow individuals to keep up to date with occurrences without time limits, which keeps them informed of the latest news and current affairs around the globe. This can be established by a recent study by Oxford University, which stated that 76% of people could receive the latest information at any time due to the information revolution by modern mass media.',
        twoDespection:'一方面，以大众媒体为主导的信息革命可以帮助个人及时获得信息。更具体地说，计算机等现代大众媒体可以让个人无时间限制地了解最新情况，从而了解全球最新新闻和时事。牛津大学最近的一项研究证实了这一点，该研究指出，由于现代大众媒体的信息革命，76%的人可以随时收到最新信息。',
        three:'On the other hand, the information revolution brought by mass media could harm social stability. To illustrate, there is a lot of sexual and violent information in the modern mass media, and this negative information induces people to conduct criminal activities, especially for young people who have poor judgment. According to the annual report of the Australian government, more than 70% of the citizens believe that modern mass media has a negative impact on social stability. ',
        threeDespection:'另一方面，大众媒体带来的信息革命可能会损害社会稳定。举例来说，现代大众媒体中有大量的性信息和暴力信息，这些负面信息诱使人们进行犯罪活动，尤其是对判断力差的年轻人来说。根据澳大利亚政府的年度报告，超过70%的公民认为现代大众媒体对社会稳定有负面影响。',
        four:'To sum up, the information revolution generated by modern mass media has not only a positive impact on individuals, such as disseminating the news, but also negative influences on society, such as the increase in crime rate.',
        fourDespection:'总之，现代大众媒体产生的信息革命不仅对个人产生了积极影响，如传播新闻，还对社会产生了消极影响，如犯罪率的上升。'
    },
    {
        index: 10,
        title:'Mass media, including TV and newspaper, have a great influence on humans, particularly on the younger generation. It has a pivotal role in shaping people_s opinions. Discuss the extent you agree or disagree. Use your own experience or examples. ',
        titleDescription:'大众传媒，包括电视和报纸，对人类有很大的影响，特别是对年轻一代。它在塑造人们的观点方面起着关键作用。讨论你同意或不同意的程度。用你自己的经验或例子。',
        one: 'There is no doubt that TV and newspapers have affected individuals through their ages. Some people think there is a great influence caused by the mass media, whereas others disagree. Personally speaking, I strongly believe that the mass media has a great influence on humans in shaping people’s opinions, particularly on the younger generation, which can be supported by the reasons as follows.',
        oneDespection:'毫无疑问，电视和报纸影响了各个年龄段的人。一些人认为大众媒体的影响很大，而另一些人则不同意。就我个人而言，我坚信大众媒体在塑造人们的观点方面对人类有很大的影响，尤其是对年轻一代的影响，这可以得到以下原因的支持。',
        two: 'First and foremost, the most important reason for my belief is that the mass media can broaden people’s horizons, especially for the younger generation, which helps people embrace more opinions. To be more specific, since the mass media provides a platform for users to share their feelings, the readers can hear more voices and comments from different perspectives, which leads to the inadvertent accumulation of opinions. For example, I have read a recent study by Oxford University, which stated that 76% of people believed that young volunteers were influenced by the mass media.',
        twoDespection:'首先，我相信最重要的原因是大众媒体可以拓宽人们的视野，尤其是对年轻一代来说，这有助于人们接受更多的观点。更具体地说，由于大众媒体为用户提供了一个分享感受的平台，读者可以从不同的角度听到更多的声音和评论，这导致了意见的无意积累。例如，我读过牛津大学最近的一项研究，该研究指出，76%的人认为年轻志愿者受到大众媒体的影响。',
        three:'In addition, the second reason for the argument is that critical thinking skills can be trained and improved through the connection with the mass media for people, particularly for the younger generation. To illustrate, since different media companies tend to transfer information with different attitudes and arguments, the readers or audiences will analyze the news rationally and critically, in which critical thinking skills will gradually be enhanced. For instance, according to the annual report of the Australian government, more than 70% of citizens stated that the idea that the mass media can help people shape their critical thinking.',
        threeDespection:'此外，这一论点的第二个原因是，人们，特别是年轻一代，可以通过与大众媒体的联系来训练和提高批判性思维技能。举例来说，由于不同的媒体公司倾向于以不同的态度和论据传递信息，读者或观众会理性地、批判性地分析新闻，从而逐渐提高批判性思维能力。例如，根据澳大利亚政府的年度报告，超过70%的公民表示，大众媒体可以帮助人们形成批判性思维。',
        four:'In conclusion, I strongly agree that people’s views can be significantly influenced by the emergence of mess media such as information sources can give people more perspectives and help people develop critical thinking.',
        fourDespection:'总之，我非常同意人们的观点会受到混乱媒体的出现的显著影响，比如信息源可以给人们更多的视角，帮助人们发展批判性思维。'
    },
    {
        index: 11,
        title:'Climate change is a concerning global issue. Who should take the responsibilities, governments, big companies or individuals?  ',
        titleDescription:'气候变化是一个令人关切的全球问题。谁应该承担责任，政府，大公司还是个人？',
        one: 'There is no doubt that climate change is a concerning global issue. Some people point out that governments should assume responsibility, whereas others would believe that big companies and individuals also have responsibilities. Personally speaking, I strongly believe that governments should take the major responsibilities for climate change, which can be supported by the reasons as follows.',
        oneDespection:'毫无疑问，气候变化是一个令人关切的全球性问题。一些人指出政府应该承担责任，而另一些人则认为大公司和个人也有责任。就我个人而言，我强烈认为政府应该对气候变化承担主要责任，这可以得到以下原因的支持。',
        two: 'The first and the most important reason for my belief is that governments have strong power to make changes. To illustrate, governments have the legislative power to set relevant rules and regulations. In this case, they can get rid of the sources that cause climate change and constrain improper actions, so governments should take responsibility for climate change. To further support the above statement, the Chinese government set a rule to prohibit coal combustion and using greener energy instead, which effectively reduces carbon emissions.',
        twoDespection:'我相信的第一个也是最重要的原因是，政府有强大的权力做出改变。举例来说，政府有立法权制定相关的规章制度。在这种情况下，他们可以消除导致气候变化的来源，并约束不当行为，因此政府应该为气候变化承担责任。为了进一步支持上述声明，中国政府制定了一项规则，禁止燃烧煤炭，转而使用更环保的能源，这有效地减少了碳排放。',
        three:'On the other hand, the second reason for this argument is that governments have sufficient funds to make all the plans into reality. This is because it is a necessary support to formulate relevant rules, cultivate talents in related fields, plan for propaganda to raise awareness regarding climate change. This can be established by a recent study that government intervention for climate change is the most effective way in a short time.',
        threeDespection:'另一方面，这种说法的第二个原因是政府有足够的资金将所有计划变成现实。这是因为制定相关规则、培养相关领域的人才、计划宣传以提高人们对气候变化的认识是必要的支持。最近的一项研究证实了这一点，即政府干预气候变化是短时间内最有效的方式。',
        four:'With all the points above, the conclusion can be made that governments play a major role in solving the climate change issue because it has more power and sufficient funds.',
        fourDespection:'综上所述，可以得出结论，政府在解决气候变化问题上发挥着重要作用，因为它拥有更多的权力和足够的资金。'
    },
    {
        index: 12,
        title:'There are many important inventions in the modern world, including antibiotics, airplanes and computers. What do you believe is the most important invention of the past hundred years? Why?   ',
        titleDescription:'现代世界有许多重要的发明，包括抗生素、飞机和计算机。你认为过去一百年里最重要的发明是什么？为什么？',
        one: 'There is no doubt that there have been many useful inventions such as antibiotics, airplanes, and computers in the past centuries. Personally speaking, I strongly believe that the computer is the most important invention in the past 100 years.',
        oneDespection:'毫无疑问，在过去的几个世纪里，有许多有用的发明，如抗生素、飞机和计算机。就我个人而言，我坚信计算机是过去100年中最重要的发明。',
        two: 'To begin with, the computer can increase the productivity of society. To illustrate, as a computer is based on a powerful database and has much stronger abilities in computing and calculating, it can help people accomplish work more efficiently than before. For example, a company could only complete market analysis in ten days by writing and calculating on the paper 100 years ago. However, this work can be finished in an hour today by creating a spreadsheet on the computer. Thus, computers can generate more productivity for human beings.',
        twoDespection:'首先，计算机可以提高社会生产力。举例来说，由于计算机基于强大的数据库，具有更强的计算和计算能力，它可以帮助人们比以前更高效地完成工作。例如，一家公司在100年前只能通过在纸上写字和计算，在十天内完成市场分析。然而，今天通过在计算机上创建电子表格，这项工作可以在一个小时内完成。因此，计算机可以为人类创造更多的生产力。',
        three:'Furthermore, the computer can help to reduce the labor cost of society. In other words, since the computer has various robust functions and the superior ability to process information than human beings, it can complete a complex work by itself instead of four or five people. Thus, direct labor costs would be reduced significantly. For instance, in the past, the laboratory of Cambridge University required four people to do scientific research about gene biology, but now they only need one scientist to finish it by manipulating computers. As a result, they saved the direct labor costs of the wages of three people.',
        threeDespection:'此外，计算机可以帮助降低社会的劳动力成本。换言之，由于计算机具有各种强大的功能和比人类优越的处理信息的能力，它可以自己完成一项复杂的工作，而不是由四五个人完成。因此，直接劳动力成本将显著降低。例如，过去剑桥大学的实验室需要四个人来做基因生物学的科学研究，但现在他们只需要一名科学家通过操纵计算机来完成。因此，他们节省了三个人工资的直接人工成本。',
        four:'To sum up, the computer is the most important invention because it can not only increase productivity but also reduce the labor cost of society. Thus, society in this technology world has been positively impacted.',
        fourDespection:'总之，计算机是最重要的发明，因为它不仅可以提高生产力，还可以降低社会的劳动力成本。因此，这个科技世界的社会受到了积极的影响。'
    },
    {
        index: 13,
        title:'Should marketing in companies producing consumer goods like food and clothing, place emphasis on the reputation of the company or short-term strategies like discount and special offers? Why?',
        titleDescription:'在生产食品和服装等消费品的公司中，营销应该强调公司的声誉还是短期战略，如折扣和特价？为什么？',
        one: 'There is no doubt that many companies use various marketing techniques to attract customers. Some companies attract customers through discounts and special offers, while others concentrate on developing brand reputation. In my opinion, companies should focus on improving their reputation, which can be supported by the reasons as follows.',
        oneDespection:'毫无疑问，许多公司使用各种营销技巧来吸引客户。一些公司通过折扣和特惠来吸引客户，而另一些公司则专注于发展品牌声誉。在我看来，公司应该专注于提高声誉，这可以由以下原因来支持。',
        two: 'First of all, by focusing on building their reputation, companies will eventually gain brand recognition from their customers. Specifically, if the company is well known by customers, they would recommend the company’s products to their friends and family, which will not only increase customers’ loyalty but also expand their customer scale. To further support the above statement, I have found a survey made by Monash University that there is a 73% increase in the customer retention rate of companies that focus on reputation strategies.  ',
        twoDespection:'首先，通过专注于建立自己的声誉，公司最终将获得客户的品牌认可。具体来说，如果公司为客户所熟知，他们会向朋友和家人推荐公司的产品，这不仅会增加客户的忠诚度，还会扩大他们的客户规模。为了进一步支持上述说法，我发现莫纳什大学的一项调查显示，专注于声誉策略的公司的客户保留率提高了73%。',
        three:'Secondly, the companies which aim to focus on their reputation will benefit from improving their market share. To illustrate, when a company strives to get a good reputation, it will invest funds to do word-of-mouth marketing for its products so that it will win a large share of the market against its competitors. There is another study by the University of Sydney, which claims that over 56% of the companies which focus on their reputation have a larger marketing share than the others in the same industry.',
        threeDespection:'其次，那些专注于声誉的公司将从提高市场份额中受益。举例来说，当一家公司努力获得良好的声誉时，它会投资资金为其产品进行口碑营销，从而在与竞争对手的竞争中赢得很大的市场份额。悉尼大学的另一项研究称，超过56%的专注于声誉的公司比同行业的其他公司拥有更大的市场份额。',
        four:'With all points above, the conclusion can be drawn that consumer goods companies should market for their reputation to promote customers’ trust and gain more market share. In this regard, companies in this industry can develop marketing strategies accordingly.',
        fourDespection:'综合以上几点，可以得出这样的结论：消费品公司应该以信誉为卖点，以提高客户的信任，获得更多的市场份额。在这方面，该行业的公司可以相应地制定营销策略。'
    },
    {
        index: 14,
        title:'You are given climate change as the field of study. Which area would you prefer? Explain why you pick this particular area of your study and give an example in the area you pick.',
        titleDescription:'你的研究领域是气候变化。你更想选哪个领域？解释你为什么选择你研究的这个特定领域，并给出一个你选择的领域的例子。',
        one: 'In recent years, climate change has provoked a fierce debate. Some people think that the negative influence of climate change is too obvious to ignore. So from my perspective, I prefer to study global warming as an area of climate change. ',
        oneDespection:'近年来，气候变化引发了激烈的争论。一些人认为气候变化的负面影响太明显了，不容忽视。因此，从我的角度来看，我更喜欢将全球变暖作为气候变化的一个领域来研究。',
        two: 'The first and the most important reason for my belief is that global warming is a serious problem as it will harm biodiversity. To be more specific, the rise in global temperature will lead to polar animals losing their habitats, such as polar bears and penguins, so it is a threat for polar species because of sea-level rise caused by higher temperatures. This can be established by a recent study by Oxford University, which stated that 76% of people believe that global warming is the major factor that affects biodiversity. ',
        twoDespection:'我相信的第一个也是最重要的原因是，全球变暖是一个严重的问题，因为它会损害生物多样性。更具体地说，全球气温的上升将导致北极熊和企鹅等极地动物失去栖息地，因此，由于气温升高导致海平面上升，这对极地物种来说是一个威胁。牛津大学最近的一项研究表明，76%的人认为全球变暖是影响生物多样性的主要因素。',
        three:'On the other hand, global warming will bring risks to the physical health of human beings. To illustrate, the emission of carbon dioxide due to human activities, which causes harm to people’s body health and makes them suffer some severe diseases, like lung cancer and breathing diseases. This can be established by a recent study by Oxford University, which stated that 34% of people with diseases are caused by global warming.',
        threeDespection:'另一方面，全球变暖将给人类的身体健康带来风险。举例来说，由于人类活动而排放的二氧化碳，对人们的身体健康造成危害，并使他们患上一些严重的疾病，如肺癌和呼吸疾病。牛津大学最近的一项研究表明，34%的疾病患者是由全球变暖引起的',
        four:'With all points above, the conclusion can be drawn that I would like to study global warming as the area of climate change as it negatively influences biodiversity and human health.',
        fourDespection:'综上所述，可以得出的结论是，我想将全球变暖作为气候变化的一个领域来研究，因为它对生物多样性和人类健康产生了负面影响。'
    },
    {
        index: 15,
        title:'There are both problems and benefits for high school students to study plays and works of theatres written centuries ago. Discuss and use your own experience. ',
        titleDescription:'对高中生来说，学习几个世纪前写的戏剧和戏剧作品既有问题也有好处。请就这个观念进行讨论，并使用你自己的经验。',
        one: 'There is a fierce debate about whether high school students should study plays and works of theatres written centuries ago. Some people think it is necessary for high school students to study old plays, while others disagree. Personally speaking, it has both problems and benefits for high school students to study plays and works of theatres written centuries ago.',
        oneDespection:'关于高中生是否应该学习几个世纪前创作的戏剧和戏剧作品，存在着激烈的争论。有些人认为高中生有必要学习老戏，而另一些人则不同意。就我个人而言，对高中生来说，学习几个世纪前创作的戏剧和戏剧作品既有问题，也有好处。',
        two: 'The key benefit of learning plays and works of theatres written hundreds of years ago is that it could help high students to widen their range of knowledge. To be more specific, through the learning process of old plays and works, high students can acquire a large amount of knowledge about ancient values, customs, and lifestyles, which can help them understand ancient history and culture. For example, I have read a recent study of Oxford University, which stated 70% of British High school students chose plays and works of theatre written centuries ago as their major resources to understand ancient history and culture. ',
        twoDespection:'学习数百年前创作的戏剧和戏剧作品的主要好处是可以帮助高中生拓宽他们的知识范围。更具体地说，通过对老戏剧和老作品的学习过程，高中生可以获得大量关于古代价值观、习俗和生活方式的知识，这可以帮助他们了解古代历史和文化。例如，我读过牛津大学最近的一项研究，该研究指出，70%的英国高中生选择了几个世纪前创作的戏剧和戏剧作品作为他们了解古代历史和文化的主要资源。',
        three:'However, the main downside of learning plays and works of theatres written hundreds of years ago is that it will increase students’ burden in high school. To illustrate, some old works are written in ancient languages like old English and Latin with abstruse meaning, which makes students have to spend more time studying and understanding ancient literature. According to the annual report of the Australian government, more than 70% of the students stated that they had difficulties studying ancient plays of theatres.',
        threeDespection:'然而，学习数百年前创作的戏剧和戏剧作品的主要缺点是会增加学生在高中的负担。举例来说，一些古老的作品是用古老的语言写的，比如古老的英语和拉丁语，含义深奥，这使得学生不得不花更多的时间学习和理解古代文学。根据澳大利亚政府的年度报告，超过70%的学生表示他们在学习古代戏剧方面有困难。',
        four:'With all points above, the conclusion can be drawn that it has both problems and benefits for high school students to study plays and works of theatres written centuries ago as it can help students to increase their knowledge base, but it will also increase their burden in the study. ',
        fourDespection:'综上所述，可以得出这样的结论：高中生学习几百年前创作的戏剧作品既有问题，也有好处，因为它可以帮助学生增加知识基础，但也会增加他们的学习负担。'
    },
    {
        index: 16,
        title:'Large shopping malls are replacing small shops. What is your opinion on this? Do you think this is a good or bad change? ',
        titleDescription:'大型购物中心正在取代小商店。你对此有什么看法？你认为这是好事还是坏事?',
        one: 'It seems that large shopping malls are replacing small shops. Personally speaking, I strongly agree that this is a good change because it brings many benefits to society.',
        oneDespection:'大型购物中心似乎正在取代小型商店。就我个人而言，我非常同意这是一个很好的改变，因为它给社会带来了很多好处。',
        two: 'On the one hand, large shopping malls can provide customers with merchandise at more affordable prices. To be more specific, as there are many different shops selling similar products in the same large shopping mall, these stores have to compete with each other and accordingly offer a lower profit margin on merchandise, which leads to lower prices for consumers. For example, research conducted by Harvard University indicates that prices of the same goods in shopping malls are 15% lower than those in small shops on average.',
        twoDespection:'一方面，大型购物中心可以以更实惠的价格为顾客提供商品。更具体地说，由于在同一个大型购物中心有许多不同的商店出售类似的产品，这些商店必须相互竞争，从而降低商品的利润率，从而降低消费者的价格。例如，哈佛大学的研究表明，购物中心的同类商品价格平均比小商店低15%。',
        three:'On the other hand, shopping in large shopping malls may save a lot of time for customers who need to purchase multiple kinds of products. To be more specific, since there are nearly all varieties of stores in the shopping mall, shoppers can complete almost all errands in the same location instead of spending too much time traveling among different small shops. For instance, according to a statistic conducted by Stanford University, it could save customers up to two hours to purchase in large shopping malls compared to the same goods in small shops.',
        threeDespection:'另一方面，在大型购物中心购物可能会为需要购买多种产品的顾客节省大量时间。更具体地说，由于购物中心几乎有各种各样的商店，购物者可以在同一地点完成几乎所有的跑腿，而不用花太多时间在不同的小商店之间旅行。例如，根据斯坦福大学的一项统计数据，与在小商店购买相同商品相比，在大型购物中心购买商品最多可以节省两个小时。',
        four:'In conclusion, it is a good change that large shopping malls are replacing small shops because large shopping malls can offer consumers more affordable prices and help consumers save a lot of time.',
        fourDespection:'总之，大型购物中心正在取代小型商店，这是一个很好的变化，因为大型购物中心可以为消费者提供更实惠的价格，并帮助消费者节省大量时间。'
    },
    {
        index: 17,
        title:'There are more and more situations where credit cards are used instead of cash. The idea of a cashless society seems to be becoming more of a reality. How realistic do you think it is? What do you see as the potential benefits or problems? ',
        titleDescription:'用信用卡代替现金的情况越来越多了。无现金社会的想法似乎越来越成为现实。你觉得它有多现实？你认为潜在的好处和问题是什么?',
        one: 'There is a heated debate that a cashless society is becoming a reality because the increasing number of people are using credit cards instead of using cash now. Some people point out that a cashless society is beneficial, whereas others are concerned about some potential problems. Personally speaking, I strongly believe that a cashless society is absolutely realistic, and it causes some potential problems such as cybercrimes.',
        oneDespection:'有一场激烈的争论认为，无现金社会正在成为现实，因为现在越来越多的人使用信用卡而不是现金。一些人指出无现金社会是有益的，而另一些人则担心一些潜在的问题。就我个人而言，我坚信无现金社会是绝对现实的，它会导致一些潜在的问题，如网络犯罪。',
        two: 'First and foremost, a cashless society is very realistic because of the rapid development of digital payment. To be more specific, there are varieties of equipment such as POS machines, Apple Pay machines, and mobile scanners that can be found everywhere, so people are more willing to use mobile phones and credit cards to purchase goods or pay for bills rather than carry lots of cash in their pockets. For example, there was a statistics report done by Melbourne University in 2017, showing that 92.7% of the merchants in Australia have POS machines or other electronic payment equipment. Thus, a cashless society is very realistic.',
        twoDespection:'首先，由于数字支付的快速发展，无现金社会是非常现实的。更具体地说，POS机、Apple Pay机和移动扫描仪等设备种类繁多，因此人们更愿意使用手机和信用卡购买商品或支付账单，而不是口袋里揣着大量现金。例如，墨尔本大学在2017年做的一份统计报告显示，澳大利亚92.7%的商户拥有POS机或其他电子支付设备。因此，无现金社会是非常现实的。',
        three:'On the other hand, a cashless society may increase the rate of cybercrimes to some extent. To illustrate, more people choose to use credit cards for payment, especially when shopping online, which raises the concern of personal information security because everyone can get access to their bank account if they can get the account holders’ personal information, such as card numbers and security code. One example is about my aunt, whose credit card information was given out, resulting in a loss of $1000 in her account due to cybercrime.',
        threeDespection:'另一方面，无现金社会可能在一定程度上提高网络犯罪率。举例来说，越来越多的人选择使用信用卡支付，尤其是在网上购物时，这引发了人们对个人信息安全的担忧，因为如果每个人都能获得账户持有人的个人信息，如卡号和安全码，他们就可以访问自己的银行账户。一个例子是关于我姑姑的，她的信用卡信息被泄露，导致她的账户因网络犯罪损失了1000美元。',
        four:'In conclusion, as more and more people are using credit cards for payment, it is very realistic a cashless society will eventually become a reality, but it may increase cybercrimes.',
        fourDespection:'总之，随着越来越多的人使用信用卡支付，无现金社会最终将成为现实是非常现实的，但这可能会增加网络犯罪。'
    },
    {
        index: 18,
        title:'Medical technology is responsible for increasing the average life expectancy. Do you think it is a curse or a blessing?',
        titleDescription:'医疗技术提高了人们的平均预期寿命。你觉得这是诅咒还是福祉？',
        one: 'There is no doubt that advanced medical technology has expanded the human_s lifespan. Some people argue that this phenomenon results in negative effects on society whereas others state it brings benefits. I strongly believe that the expansion of the human_s lifespan caused by the advanced medical technology is a curse, which can be supported by the reasons as follows.',
        oneDespection:'毫无疑问，先进的医疗技术延长了人类的寿命。一些人认为这种现象会对社会产生负面影响，而另一些人则认为它会带来好处。我坚信，先进的医疗技术导致人类寿命的延长是一种诅咒，其原因如下。',
        two: 'The first reason is that the expansion of human_s lifespan owing to medical technology exacerbates the shortage of resources supply. Specifically, since advanced technology expands human_s life, the global population will increase dramatically, so more resources are needed to supply the expanding global population. This can be supported by my own experience that the food supply in my home country has fallen by 20% due to the impact of the expansion of its residents_ lifespan.',
        twoDespection:'第一个原因是医疗技术导致人类寿命的延长加剧了资源供应的短缺。具体来说，由于先进技术扩大了人类的生活，全球人口将急剧增加，因此需要更多的资源来供应不断扩大的全球人口。这可以从我自己的经历中得到支持，即由于居民寿命延长的影响，我的祖国的粮食供应下降了20%。',
        three:'On the other hand, the second reason is that the expansion of a human_s lifespan caused by advanced medical technology increases the governments_ financial burden. This is because governments need to spend more money on pension welfare to support the living of the elderly as they live longer. This can be supported by a recent study conducted by Oxford University that the British government_s budget on pension has increased significantly by 80% as the average lifespan of British residents has risen by 2 years.',
        threeDespection:'另一方面，第二个原因是先进医疗技术导致的人类寿命延长增加了政府的财政负担。这是因为随着老年人寿命的延长，政府需要在养老金福利上投入更多资金来支持他们的生活。牛津大学最近进行的一项研究支持了这一点，该研究表明，随着英国居民平均寿命的延长，英国政府的养老金预算大幅增加了80%。',
        four:'With all the points above, the conclusion can be drawn that the expansion of the human_s lifespan enabled by advanced technology is a curse because it exacerbates the shortage of resources and increases the governments_ financial burden. ',
        fourDespection:'综上所述，可以得出这样的结论：先进技术使人类寿命的延长是一种诅咒，因为它加剧了资源短缺，增加了政府的财政负担。'
    },
    {
        index: 19,
        title:'Some people point that experiential learning (i.e. learning by doing) can work well in formal education. However, others think a traditional form of teaching is the best. Do you think experiential learning is beneficial in high school or college? ',
        titleDescription:'有些人指出，体验式学习（即通过“实践”来学习）在正统教育中效果很好。然而，其他人认为传统的教学形式是最好的。你认为体验式学习在高中或大学是有益的吗?',
        one: 'There is no doubt that experiential learning has become increasingly popular in schools. Some people state that experiential learning can work well in formal education, whereas others argue that a traditional form of teaching is the best. I strongly believe that experiential learning is beneficial in high schools and colleges, which can be supported by the reasons as follows.',
        oneDespection:'毫无疑问，体验式学习在学校里越来越受欢迎。一些人认为体验式学习在正规教育中效果很好，而另一些人则认为传统的教学形式是最好的。我坚信体验式学习在高中和大学是有益的，这可以由以下原因来支持。',
        two: 'First and foremost, experiential learning helps students to acquire and memorize knowledge more easily in high school or college. To be more specific, conducting hands-on experiments and watching the real process of experiments by themselves enhance students_ memory and interpretation of the knowledge, so they can understand concepts more deeply through practice than only read them in textbooks. This can be supported by my own experience that I could memorize knowledge by doing experiments more profoundly compared with just learning theories in books.',
        twoDespection:'首先，体验式学习有助于学生在高中或大学更容易地获得和记忆知识。更具体地说，亲自动手做实验和观看实验的真实过程，可以增强学生对知识的记忆和理解，使他们能够通过实践更深入地理解概念，而不仅仅是在课本上阅读。这可以从我自己的经验中得到支持，与在书中学习理论相比，我可以通过做实验更深刻地记住知识。',
        three:'On the other hand, experiential learning is helpful for students to develop practical skills. Explicitly, with the opportunity to apply concepts in textbooks in real cases, practical experience can be learned and built on to cultivate pragmatic techniques, such as interpersonal skills. This can be supported by a recent study conducted by Oxford University that 90% of students who graduate from experiential learning programs show a better performance in practical skills compared with their peers.',
        threeDespection:'另一方面，体验式学习有助于学生发展实践技能。明确地说，有机会将教科书中的概念应用到实际案例中，可以学习和借鉴实践经验来培养语用技巧，如人际交往技能。牛津大学最近进行的一项研究支持了这一点，该研究表明，与同龄人相比，90%从体验式学习项目毕业的学生在实践技能方面表现更好。',
        four:'With all the points above, the conclusion can be drawn that experiential learning is beneficial in high schools and colleges because it helps students to memorize knowledge and acquire practical skills.',
        fourDespection:'综合以上几点，可以得出结论：体验式学习有助于学生记忆知识和获得实践技能，在高中和大学是有益的。'
    },
    {
        index: 20,
        title:'Should parents be held legally responsible for the actions of their children? Do you agree with this opinion? Support your position with your own study, experience or observations. ',
        titleDescription:'父母应该为孩子的行为承担法律责任吗?你同意这个观点吗？用你自己的研究、经验或观察来支持你的观点。',
        one: 'There is no doubt that parents should be responsible for taking care of their children. Some people argue that parents should shoulder the responsibility for the actions of their children, whereas others disagree. I strongly believe that parents should be held legally responsible for the actions of their children, which can be supported by the reasons as follows.',
        oneDespection:'毫无疑问，父母应该负责照顾他们的孩子。一些人认为父母应该为孩子的行为承担责任，而另一些人则不同意。我坚信，父母应该对孩子的行为承担法律责任，这可以通过以下理由来支持。',
        two: 'The first reason is that parents should be held legally responsible for the actions of their children as their behavior is directly influenced by their parents. Specifically, children’s misconduct or illegal behaviors are not the faults of themselves but the faults of their parents who fail to instruct their children to identify what is right or wrong, since children have yet to establish a mature judgment. This can be established by my observations that some of my friends conducted stealing simply because their parents never told them such behaviors were illegal.',
        twoDespection:'第一个原因是父母应该对孩子的行为承担法律责任，因为他们的行为直接受到父母的影响。具体来说，儿童的不当行为或非法行为不是他们自己的错，而是他们的父母的错，他们没有指导孩子识别什么是对的或错的，因为孩子还没有建立成熟的判断。这可以从我的观察中得到证实，我的一些朋友之所以进行偷窃，仅仅是因为他们的父母从未告诉他们这种行为是非法的。',
        three:'On the other hand, the second reason is that parents should be held legally responsible for their children_s actions, which makes them exercise their duty of supervision. This is because parents will educate their children to establish a correct code of morality and to conduct legally compliant behaviors to avoid punishments by law. This can be supported by my own experience that I always supervise my children_s actions because I do not want to be penalized by the legislation.',
        threeDespection:'另一方面，第二个原因是父母应该对孩子的行为承担法律责任，这使他们行使了监督义务。这是因为父母会教育孩子建立正确的道德规范，并进行合法的行为，以避免受到法律的惩罚。这可以从我自己的经历中得到支持，我总是监督我孩子的行为，因为我不想受到法律的惩罚。',
        four:'With all the points above, the conclusion can be drawn that parents should be held legally responsible for the actions of their children because children_s actions are directly influenced by their parents, and this legal responsibility forces them to exercise their duty of supervision.',
        fourDespection:'综上所述，可以得出这样的结论：父母应该对孩子的行为承担法律责任，因为孩子的行为直接受到父母的影响，而这种法律责任迫使他们履行监督义务。'
    },
    {
        index: 21,
        title:'Some universities deduct students’ marks if assignments are given late. What is your opinion and give your recommendations?',
        titleDescription:'某些大学会对迟交的作业进行扣分。你的看法是什么？并给出你的建议。',
        one: 'There is no doubt that some universities deduct students_ work if their assignment is given late. Some people state that this regulation is beneficial to students_ studies, whereas others disagree. I strongly believe that deducting students_ marks if the assignment is given late has a positive effect on their studies. ',
        oneDespection:'毫无疑问，有些大学会因为学生作业迟交而扣减他们的作业。一些人认为这一规定有利于学生的学习，而另一些人则不同意。我坚信，如果作业交得晚，扣除学生的分数对他们的学习有积极影响。',
        two: 'The reason why deducting students_ marks if their assignment is overdue is beneficial to students is that it helps to improve students_ time management. Specifically, students are forced to be punctual to avoid punishment, so students start to develop an awareness of time and punctuality. For example, I enhanced my time management skills during my university time when I tried to avoid my school_s strict punishments on students_ marks in terms of late submissions.',
        twoDespection:'作业逾期扣分对学生有利的原因是有助于提高学生的时间管理能力。具体来说，学生们被迫准时以避免惩罚，因此学生们开始培养时间和准时意识。例如，我在大学期间提高了时间管理技能，当时我试图避免学校对学生迟交成绩的严格惩罚。',
        three:'As for the alternative action, universities should help students make a staged timetable for the progress of their assignments. This is reasonable because a staged timetable can remind them how much time they will need to complete their work to avoid missing deadlines. This can be supported by a recent report conducted by Oxford University that students who make a staged timetable for their work are 80% less likely to submit their assignments late compared to their classmates who do not.',
        threeDespection:'至于替代行动，大学应该帮助学生制定一个分阶段的作业进度时间表。这是合理的，因为分阶段的时间表可以提醒他们需要多少时间来完成工作，以避免错过最后期限。牛津大学最近的一份报告支持了这一点，该报告称，与不制定分阶段作业时间表的同学相比，制定分阶段工作时间表的学生迟交作业的可能性低80%。',
        four:'With all the points above, the conclusion can be drawn that deducting students_ marks if an assignment is given late is beneficial to students because it improves students_ time management. In addition, an alternative action to avoid submitting assignments late is to make a staged timetable. ',
        fourDespection:'综合以上几点，可以得出这样的结论：如果作业迟交，扣减学生的分数对学生是有益的，因为它可以改善学生的时间管理。此外，避免迟交作业的另一种措施是制定分阶段的时间表。'
    },
    {
        index: 22,
        title:'In order to study effectively, it requires comfort, peace and time. So it is impossible for a student to combine learning and employment at the same time, because one distracts the other. Is it realistic to combine them at the same time in our life today? Support your opinion with examples. ',
        titleDescription:'有效的学习需要舒适平静的状态和充分的时间。因此一个学生不可能同时把学习和工作结合起来，因为两者会相互干扰。在我们今天的生活中，把它们同时结合起来现实吗?用例子来支持你的观点.',
        one: 'There is no doubt that studying needs time, peace and comfort while employment needs the same thing. Some people state that it is impossible to combine those two because one distracts one another, whereas others disagree. I strongly believe that combining study with employment is realistic in our life, which can be supported by the reasons as follows. ',
        oneDespection:'毫无疑问，学习需要时间、平静和舒适，而就业也需要同样的东西。有些人表示，不可能将这两者结合起来，因为其中一种会分散彼此的注意力，而另一些人则不同意。我坚信，学习与就业相结合在我们的生活中是现实的，这可以得到以下原因的支持。',
        two: 'The first reason is that individuals can combine study with employment by making use of the time saved by using high-tech equipment. Specifically, employees’ working efficiency has been significantly improved in recent years with the assistance of the computer, which allows them to have more time to study after completing their jobs early, so it is realistic for students to combine study and work together. This can be supported by my own experience that I can study in the afternoon even during working hours because I can finish my work in the morning owing to high-tech tools.',
        twoDespection:'第一个原因是个人可以利用高科技设备节省的时间，将学习与就业结合起来。具体来说，近年来，在计算机的帮助下，员工的工作效率显著提高，这使他们在提前完成工作后有更多的时间学习，因此学生将学习和工作结合起来是现实的。这可以从我自己的经验中得到支持，即使在工作时间，我也可以在下午学习，因为有了高科技工具，我可以在早上完成工作。',
        three:'On the other hand, the second reason why students combining study with employment is realistic is that there are various online courses available that provide high flexibility for them in terms of their arrangements. Consequently, students can study at night or during weekends at home without distracting their part-time jobs during working hours. This can be supported by a recent report conducted by Oxford University that 60% of British people succeed in making a balance between study and employment by attending online courses at night.',
        threeDespection:'另一方面，学生将学习与就业相结合是现实的第二个原因是，有各种在线课程可供选择，在安排方面为他们提供了高度的灵活性。因此，学生可以在晚上或周末在家学习，而不会在工作时间分散他们的兼职工作。牛津大学最近的一份报告支持了这一点，该报告称，60%的英国人通过晚上参加在线课程，成功地在学习和就业之间取得了平衡。',
        four:'With all the points above, the conclusion can be drawn that combining study with employment is realistic because students can conduct jobs in their holidays, and employees can study through online courses. ',
        fourDespection:'综合以上几点，可以得出结论，将学习与就业相结合是现实的，因为学生可以在假期从事工作，员工可以通过在线课程学习。'
    },
    {
        index: 23,
        title:'The world’s governments and organizations are facing a lot of issues. Which do you think is the most pressing problem for the inhabitants on our planet? And give solutions.',
        titleDescription:'世界各国政府和组织正面临着许多问题。你认为对地球上的居民来说，哪一个是最紧迫的问题？并给出解决方案。',
        one: 'There is no doubt that the world_s governments and organizations are facing many issues, which have become the pressing problems for the inhabitants of our planet. There are serious problems on the earth, such as climate change, aging, and globalization. In my opinion, I believe that the most pressing problem globally is climate change and there are some solutions to address this issue, which can be supported by the following reasons. ',
        oneDespection:'毫无疑问，世界各国政府和组织正面临许多问题，这些问题已成为我们星球上居民的紧迫问题。地球上存在着严重的问题，如气候变化、老龄化和全球化。在我看来，我认为全球最紧迫的问题是气候变化，有一些解决方案可以解决这个问题，这可以得到以下原因的支持。',
        two: 'The first and the most important reason for my belief is that climate change will reduce biodiversity. To be more specific, global warming not only changed human living conditions but also destroyed the animals living environment, which will decrease the number of these species. For example, the statistics showed that in China, more than 100 species are endangered due to the rising temperature that damaged their living condition.',
        twoDespection:'我相信的第一个也是最重要的原因是气候变化会减少生物多样性。更具体地说，全球变暖不仅改变了人类的生活条件，还破坏了动物的生存环境，这将使这些物种的数量减少。例如，统计数据显示，在中国，有100多种物种因气温上升而濒临灭绝，这损害了它们的生存条件。',
        three:'However, the main solution to deal with climate change is that the government should encourage people to use clean energy such as solar energy. The reason is that solar power is sustainable energy, which can reduce greenhouse gases as well as protect the earth_s natural resources. According to the annual report of the Australian government, more than 70% of the citizens stated that Melbourne is encouraged to utilize solar power in public transportation, which will reduce carbon dioxide emissions.',
        threeDespection:'然而，应对气候变化的主要解决方案是，政府应该鼓励人们使用太阳能等清洁能源。原因是太阳能是可持续能源，可以减少温室气体，保护地球的自然资源。根据澳大利亚政府的年度报告，超过70%的公民表示，鼓励墨尔本在公共交通中使用太阳能，这将减少二氧化碳排放。',
        four:'With all the points above, the conclusion can be made that climate change is the most important problem in society that many governments are facing, so we should encourage societies to use solar energy to replace fossil fuels to improve this situation. ',
        fourDespection:'综上所述，可以得出结论，气候变化是许多政府面临的社会中最重要的问题，因此我们应该鼓励社会使用太阳能代替化石燃料来改善这种情况。'
    },
    {
        index: 24,
        title:'How does the design of building affect, either positively or negatively, where people work and live? ',
        titleDescription:'建筑设计如何影响人们工作和生活的地方的，无论是积极的还是消极的？',
        one: 'There is no doubt that the design of the building has a dramatic influence on people_s lives. Personally speaking, I strongly believe that there are both positive and negative effects on people’s work and life, which can be supported by the reasons as follows.',
        oneDespection:'毫无疑问，这座建筑的设计对人们的生活产生了巨大的影响。就我个人而言，我坚信对人们的工作和生活既有积极的影响，也有消极的影响，原因如下。',
        two: 'The key benefit of a good design of buildings is that it makes people’s lives safer. To be more specific, buildings with safety facilities, such as fire exits and emergency access, can allow people to evacuate quickly when a fire breaks out. For example, this can be established by a recent study by Oxford University, which stated that 76% of people believe that a good design of a building can make people’s lives safer.',
        twoDespection:'一个好的建筑设计的主要好处是它能让人们的生活更安全。更具体地说，有安全设施的建筑，如消防出口和紧急通道，可以让人们在火灾发生时迅速疏散。例如，牛津大学最近的一项研究证实了这一点，该研究指出，76%的人认为良好的建筑设计可以让人们的生活更安全。',
        three:'On the other hand, the main downside of a bad design of buildings is that it may decrease people’s working efficiency. To illustrate, people can_t focus on a task in an open-plan office as they are distracted by someone_s conversations and general background noise. For example, according to the annual report of the New Zealand government, more than 70% of the citizens believe that a bad design of buildings will decrease people’s working efficiency.',
        threeDespection:'另一方面，糟糕的建筑设计的主要缺点是可能会降低人们的工作效率。举个例子，在开放式办公室里，人们无法专注于一项任务，因为他们被别人的谈话和一般的背景噪音分散了注意力。例如，根据新西兰政府的年度报告，超过70%的公民认为糟糕的建筑设计会降低人们的工作效率。',
        four:'With all the points above, the conclusion can be made that there are both positive and negative effects on people’s work and life because it can guarantee people’s safety but it will lower their working performance. ',
        fourDespection:'综上所述，可以得出这样一个结论：对人们的工作和生活既有积极的影响，也有消极的影响，因为它可以保证人们的安全，但会降低他们的工作表现。'
    },
    {
        index: 28,
        title:'Some people argue that experience is the best teacher. Life experiences can teach more effectively than books or formal school education. How far do you agree with this idea? Support your opinion with reasons and/or your personal experience. ',
        titleDescription:'有些人认为经验是最好的老师。生活经验比书本或正规学校教育更有效。你在多大程度上同意这个想法？用理由和/或你的个人经历来支持你的观点。',
        one: 'There is no doubt that life experiences can teach more effectively than books or formal school education. Some people point out that experience is the best teacher, whereas others disagree. Personally speaking, I strongly believe that life experiences are more beneficial than books or formal school education, which can be supported as follows. ',
        oneDespection:'毫无疑问，生活经验比书本或正规学校教育更能有效地进行教学。有些人指出经验是最好的老师，而另一些人则不同意。就我个人而言，我坚信生活经历比书籍或正规学校教育更有益，这可以得到以下支持。',
        two: 'The first and the most important reason for my belief is that life experiences help students understand and memorize knowledge more easily because life experience generated would enhance students’ memory and interpretation of the knowledge by conducting experiments or watching the real process of the experiments. To further support my statement, I could memorize knowledge by forming a life experience more profoundly compared to just learning theories from books or formal education.',
        twoDespection:'我相信的第一个也是最重要的原因是，生活经验有助于学生更容易地理解和记忆知识，因为产生的生活经验会通过进行实验或观看实验的真实过程来增强学生对知识的记忆和解释。为了进一步支持我的说法，与仅仅从书本或正规教育中学习理论相比，我可以通过形成更深刻的生活体验来记忆知识。',
        three:'The second reason for my argument is that life experience is more valuable for students to develop practical skills than books or formal education, which is reasonable because with the opportunities applying textbook concepts in real cases, practical experience can be learned and accumulated to cultivate skills. This can be established by a recent study of Oxford University, which stated that 76% of students with experiential learning experience have better performance in practical skills compared to peers. ',
        threeDespection:'我提出这一论点的第二个原因是，生活经验对学生发展实践技能比书籍或正规教育更有价值，这是合理的，因为有机会将教科书概念应用到实际案例中，实践经验可以被学习和积累来培养技能。牛津大学最近的一项研究证实了这一点，该研究表明，与同龄人相比，76%有体验式学习经验的学生在实践技能方面表现更好。',
        four:'With all the points above, the conclusion can be made that life experience can be a better teacher compared to textbooks and formal education because it can enhance students’ understanding, memory, and practical skills. In this regard, governments should devote sufficient funding, and public awareness should be arisen to improve the situation.',
        fourDespection:'综上所述，我们可以得出这样的结论：与课本和正规教育相比，生活经验可以成为一个更好的老师，因为它可以增强学生的理解、记忆和实践技能。在这方面，政府应该投入足够的资金，并提高公众的意识来改善这种情况。'
    },
    {
        index: 29,
        title:'With the increase of digital media available online, the role of the library has become obsolete. Universities should only procure new digital media rather than constantly update textbooks. Discuss both the advantages and disadvantages of this position and give your own point of view. ',
        titleDescription:'随着在线数字媒体的增加，图书馆的作用已经过时。大学应该只购买数字材料，而不是不断更新教科书。讨论这个职位的优点和缺点，并给出你自己的观点。',
        one: 'There is no doubt that with the increase of digital media available online, the role of the library has become obsolete. Some people argue that universities should only procure new digital media rather than constantly update textbooks, some disagree. As far as I am concerned, I tend to believe that there are both advantages and disadvantages of only offering digital materials rather than constantly textbooks, which can be supported by the following reasons.',
        oneDespection:'毫无疑问，随着在线数字媒体的增加，图书馆的作用已经过时。有些人认为，大学应该只采购新的数字媒体，而不是不断更新教科书，有些人不同意。就我而言，我倾向于认为只提供数字材料而不是不断提供教科书既有优点也有缺点，这可以由以下原因来支持。',
        two: 'The key benefit of digital materials is that they are more accessible for university students. To be more specific, university students can quickly and easily locate and attain the information they need by only using the “search” button on the digital library portal, instead of scanning thousands of paper textbooks for a couple of hours. For instance, I read a recent study conducted by Cambridge University, illustrating that 76% of British students claim that digital materials shorten their time tracking information.',
        twoDespection:'数字材料的主要好处是大学生更容易获得这些材料。更具体地说，大学生只需使用数字图书馆门户网站上的“搜索”按钮，而不是扫描数千本纸质教科书几个小时，就可以快速轻松地定位和获取所需信息。例如，我读到剑桥大学最近进行的一项研究，该研究表明76%的英国学生声称数字材料缩短了他们追踪信息的时间。',
        three:'The main downside of using digital textbooks is that the expenditure on new digital media can create a financial burden for universities. To illustrate, universities will have to pay extra money to license the sources of digital materials, which are usually more expensive than printed versions. This can be further supported by a report, which stated that the university’s yearly expenditure has increased by 25% after offering digital materials, which has become a financial burden for universities. ',
        threeDespection:'使用数字教科书的主要缺点是，在新的数字媒体上的支出会给大学带来财政负担。举例来说，大学将不得不支付额外的费用来许可数字材料的来源，这些材料通常比印刷版更贵。一份报告进一步支持了这一点，该报告指出，在提供数字材料后，该大学的年度支出增加了25%，这已成为大学的财政负担。',
        four:'With all the points above, the conclusion can be made that there are both advantages and disadvantages for universities procuring new digital media rather than constantly textbooks as it can save students time, but it will increase the financial burden of universities.',
        fourDespection:'综上所述，可以得出这样的结论：大学购买新的数字媒体而不是不断购买教科书既有优点也有缺点，因为这可以节省学生的时间，但会增加大学的财政负担。'
    },
    {
        index: 30,
        title:'As cities are expanding, some people claim governments should look forward to creating better networks of public transport available for everyone rather than building more roads for vehicle owning population. What’s your opinion? Give some examples or experience to support. ',
        titleDescription:'随着城市的扩张，一些人声称，政府应该着眼于为每个人创造更好的公共交通网络，而不是为拥有汽车的人口建造更多的道路。你的意见是什么?给出一些例子或经验来支持。',
        one: 'There is no doubt that our cities are expanding rapidly. Some people point out that governments should create better networks of public transport, whereas others would believe that the government should build more roads for vehicle owning population. Personally speaking, I strongly believe that creating more networks of public transport is more necessary. ',
        oneDespection:'毫无疑问，我们的城市正在迅速扩张。一些人指出，政府应该建立更好的公共交通网络，而另一些人则认为政府应该为拥有车辆的人口修建更多的道路。就我个人而言，我坚信创建更多的公共交通网络是更必要的。',
        two: 'The first and the most important reason for my belief is that building better networks of public transport can eliminate air pollution. To be more specific, public transport, which is based on electricity, is much more environmentally friendly because it has fewer sulfide emissions by using clean energy. As a result, air pollution can be reduced to a certain extent. For example, according to a study conducted by Cambridge University, sulfide emissions were reduced by 10% in 2016 after the UK government put two more subways into operation. Furthermore, in that year, the air pollution index was reduced by 5%. ',
        twoDespection:'我相信，第一个也是最重要的原因是，建立更好的公共交通网络可以消除空气污染。更具体地说，以电力为基础的公共交通更环保，因为它使用清洁能源减少了硫化物排放。因此，空气污染可以在一定程度上减少。例如，根据剑桥大学的一项研究，2016年英国政府又开通了两条地铁后，硫化物排放量减少了10%。此外，在那一年，空气污染指数下降了5%。',
        three:'The second reason for this argument is that better networks of public transport can relieve traffic congestion. In other words, public transport can convey more people than individual automobiles in much less space, which helps riders avoid the stress that comes from daily driving in highly congested areas. Therefore, people can save their commuting time during rush hours. To further support the above statement, in the past few years, I spent more than one-hour driving from the workplace to home. However, since railways are built in my city this year, driving home only costs half an hour, which brings great convenience to me. ',
        threeDespection:'这一论点的第二个原因是，更好的公共交通网络可以缓解交通拥堵。换言之，公共交通比私家车可以在更小的空间内运送更多的人，这有助于乘客避免在高度拥堵的地区日常驾驶带来的压力。因此，人们可以在高峰时段节省通勤时间。为了进一步支持上述说法，在过去的几年里，我花了一个多小时从工作场所开车回家。然而，由于今年我所在的城市建了铁路，开车回家只需要半个小时，这给我带来了极大的便利。',
        four:'With all the points above, the conclusion can be made that the government should build better networks of public transport because it can eliminate not only air pollution but also relieve traffic congestion.  ',
        fourDespection:'综上所述，我们可以得出这样的结论：政府应该建立更好的公共交通网络，因为它不仅可以消除空气污染，还可以缓解交通拥堵。'
    },
    {
        index: 31,
        title:'The time people devote in jobs leaves very little time for personal life. How widespread is the problem? What problem will this shortage of time cause?',
        titleDescription:'人们投入工作的时间留给个人生活的时间很少。这个问题有多普遍?时间短缺会导致什么问题？',
        one: 'Many people argue that the time people devote to jobs leaves very little time for personal life. Personally speaking, I strongly believe this trend is extremely widespread, and the shortage of time in personal life will cause serious problems, which will be explained by the following reasons.',
        oneDespection:'许多人认为，人们投入工作的时间留给个人生活的时间很少。就我个人而言，我坚信这种趋势非常普遍，个人生活中时间的短缺会导致严重的问题，这可以通过以下原因来解释。',
        two: 'First and foremost, people failing to balance life and work is extremely widespread because of high competition in the job market. To be more specific, since people are facing highly competitive job tasks, they have to sacrifice their leisure time to complete their workloads. For example, I have read a recent study of Oxford University stating that 80% of people believe it is extremely widespread that people have spent too much time in jobs.',
        twoDespection:'首先，由于就业市场的高度竞争，人们无法平衡生活和工作的现象极为普遍。更具体地说，由于人们面临着竞争激烈的工作任务，他们不得不牺牲业余时间来完成工作量。例如，我读过牛津大学最近的一项研究，该研究指出，80%的人认为人们在工作中花费太多时间的现象非常普遍。',
        three:'Moreover, this shortage of time in personal life will cause family issues. To be more explicit, since less time is spent on personal life, it is quite hard for people to take care of their spouse and children, causing family fights and relationship breakdown. For instance, a recent study conducted by Cambridge University shows that 52% of family issues are caused by the imbalance between working time and leisure time.',
        threeDespection:'此外，这种个人生活时间的短缺会导致家庭问题。更明确地说，由于花在个人生活上的时间较少，人们很难照顾他们的配偶和孩子，导致家庭争吵和关系破裂。例如，剑桥大学最近进行的一项研究表明，52%的家庭问题是由工作时间和休闲时间之间的不平衡引起的。',
        four:'In conclusion, the phenomenon that people devote plenty of time to jobs and leave little time for personal life is extremely widespread, which causes many serious family issues. ',
        fourDespection:'总之，人们把大量的时间花在工作上，而把很少的时间留给个人生活的现象非常普遍，这导致了许多严重的家庭问题。'
    },
    {
        index: 32,
        title:'Nowadays, it is increasingly more difficult to maintain the right balance between work and other aspects of one’s life, such as time with family and leisure needs. How important do you think is this balance? Why do people find it hard to achieve? ',
        titleDescription:'如今，在工作和生活的其他方面，比如与家人相处的时间和休闲需求之间保持平衡越来越难了。你认为这种平衡有多重要？为什么人们觉得这个平衡很难实现？',
        one: 'There is a controversy about work-life balance. Some people think it is not crucial, whereas others disagree. Personally speaking, maintaining the right balance between work and other aspects of life is important. However, it is difficult to achieve, which can be supported as follows.',
        oneDespection:'关于工作与生活的平衡存在争议。有些人认为这并不重要，而另一些人则不同意。就我个人而言，在工作和生活的其他方面保持适当的平衡是很重要的。然而，这是很难实现的，这可以得到以下支持。',
        two: 'On the one hand, keeping the balance between work and other aspects of people’s life can increase working efficiency. To illustrate, to maintain this balance, people schedule some time for recreation, such as seeing a movie. Such balance helps boost working efficiency as people can devote more energy and concentrate more on the work or even get inspiration with a relaxed mind after relaxation. For example, yesterday, I spent three hours struggling to complete my thesis, but I got an idea to complete my dissertation in just 30 minutes after I rested for a while.',
        twoDespection:'一方面，保持工作和人们生活其他方面之间的平衡可以提高工作效率。举例来说，为了保持这种平衡，人们会安排一些时间进行娱乐，比如看电影。这种平衡有助于提高工作效率，因为人们可以投入更多的精力，更加专注于工作，甚至在放松后以放松的心态获得灵感。例如，昨天，我花了三个小时努力完成论文，但在休息了一段时间后，我想到了在30分钟内完成论文的想法。',
        three:'However, it is difficult for people to achieve a balance between work and other aspects of life because of limited time and energy. To elaborate, a burdensome working schedule accounts for the majority of the day and leaves no time for other activities. Moreover, after long working hours, people are exhausted and have no energy and desire to engage in recreational activities, so achieving this balance will be hard. For instance, after the tiring night shifts in Coles supermarket last Tuesday, I refused to go to a club with my friends because I had no energy and just wanted to have a rest at home.',
        threeDespection:'然而，由于时间和精力有限，人们很难在工作和生活的其他方面之间取得平衡。详细来说，繁重的工作日程占据了一天的大部分时间，没有时间进行其他活动。此外，经过长时间的工作，人们已经筋疲力尽，没有精力和欲望从事娱乐活动，因此很难实现这种平衡。例如，上周二在Coles超市上了疲惫的夜班后，我拒绝和朋友一起去俱乐部，因为我没有精力，只想在家休息。',
        four:'In conclusion, achieving a balance between work and private life can achieve a better working performance, but it is hard to achieve because of limited time and energy. ',
        fourDespection:'总之，在工作和私人生活之间取得平衡可以获得更好的工作表现，但由于时间和精力有限，很难实现。'
    },
    {
        index: 33,
        title:'In our technological world, the number of new inventions has been evolving on a daily basis. Please describe a new invention and explain the impact, either beneficial or detrimental, that you feel it has had on society.',
        titleDescription:'在我们的技术世界里，新发明的数量每天都在变化。请描述一项新发明，并解释你认为它对社会产生了有益或有害的影响。',
        one: 'As the technological world evolved a lot, there is no doubt that many useful inventions have emerged in recent years. Personally speaking, I strongly believe that the computer is a recent beneficial invention. In this essay, this invention will be described and its positive influence will also be discussed as follows. ',
        oneDespection:'随着科技世界的不断发展，毫无疑问，近年来出现了许多有用的发明。就我个人而言，我坚信计算机是最近的一项有益发明。在本文中，本发明将被描述，其积极影响也将被讨论如下。',
        two: 'To begin with, a computer is a new invention that is an electronic device for storing and processing data. To be more specific, a computer takes data and instructions from a user and then processes and displays the data. Besides, it is also based on a powerful database and has much stronger abilities in computing and calculating. For example, a recent study by Oxford University, which stated that 76% of people believed that computer is one of the most useful inventions during the recent centuries because of its strong data processing capability.',
        twoDespection:'首先，计算机是一项新发明，它是一种用于存储和处理数据的电子设备。更具体地说，计算机从用户那里获取数据和指令，然后处理和显示数据。此外，它还基于强大的数据库，具有更强的计算和计算能力。例如，牛津大学最近的一项研究表明，76%的人认为计算机是近几个世纪最有用的发明之一，因为它具有强大的数据处理能力。',
        three:'Furthermore, a computer, a recent beneficial invention, can help reduce labor cost in society. To illustrate, since the computer has various robust functions and a superior ability to process information, it can complete a complex task by itself instead of involving multiple people. Thus, direct labor costs would be reduced significantly if such tool is in use. For instance, according to the annual report of the Australian government, more than 30% of direct labor cost has been reduced after computers are adopted in companies. ',
        threeDespection:'此外，计算机，最近的一项有益发明，可以帮助降低社会的劳动力成本。举例来说，由于计算机具有各种强大的功能和优越的信息处理能力，它可以自己完成复杂的任务，而不是涉及多个人。因此，如果使用这种工具，直接人工成本将显著降低。例如，根据澳大利亚政府的年度报告，公司采用计算机后，直接劳动力成本降低了30%以上。',
        four:'To sum up, the recently emerging invention, computer, can help reduce the labor expenditure. Thus, society in this technology world has been positively impacted.',
        fourDespection:'总之，最近出现的发明，计算机，可以帮助减少劳动力支出。因此，这个科技世界的社会受到了积极的影响。'
    },
    {
        index: 34,
        title:'Television has many functions to play in everyone_s life. For some it_s relaxation; for some, it is the companion. To what extent do you think the statement is true? Please provide your argument and supporting evidence from your own experience. ',
        titleDescription:'电视在每个人的生活中有许多功能。对有些人来说电视让他们放松，对一些人来说电视是他们的陪伴。你认为这种说法在多大程度上是正确的？请从你自己的经历中提供你的论点和支持性证据。',
        one: 'There is no doubt that television has many functions to play in everyone_s life.Personally speaking, I strongly agree that television can make us feel relaxed and it also plays a role as a companion, which can be supported by the reasons as follows.',
        oneDespection:'毫无疑问，电视在每个人的生活中都有许多作用。就我个人而言，我非常同意电视可以让我们感到放松，它也起到了陪伴的作用，这可以得到以下原因的支持。',
        two: 'The first and most important reason for my belief is that television can make people more relaxed as watching TV is a good way to reduce people_s pressure. To be more specific, TV is a good entertainment tool, providing many interesting shows, so people will feel happy and forget about their worries when they are watching TV shows. For example, I have read a recent study by Oxford University, which states that 90% of people believe that TV can help to relax their mind.',
        twoDespection:'我相信的第一个也是最重要的原因是电视可以让人们更放松，因为看电视是减轻人们压力的好方法。更具体地说，电视是一个很好的娱乐工具，提供了许多有趣的节目，所以人们在看电视节目时会感到快乐，忘记烦恼。例如，我读过牛津大学最近的一项研究，该研究表明，90%的人认为电视可以帮助他们放松身心。',
        three:'In addition, it can be a companion, especially for people who are staying at home lonely. To illustrate, it provides a wide range of programs such as movies and TV plays, so people can get voices and stories from these television programs to kill time and reduce their loneliness. For example, I have read an annual report of the New Zealand government, which stated that 76% of citizens believe that TV can be a good companion for people to pass time.',
        threeDespection:'此外，它还可以成为伴侣，尤其是对于那些孤独地呆在家里的人来说。举例来说，它提供了广泛的节目，如电影和电视剧，因此人们可以从这些电视节目中获得声音和故事，以消磨时间，减少孤独感。例如，我读过新西兰政府的一份年度报告，其中指出76%的公民认为电视可以成为人们打发时间的好伴侣。',
        four:'With all the points above, the conclusion can be made that television is an essential tool in people’s daily life because it can make us feel relaxed and it also plays a role as a companion.',
        fourDespection:'综上所述，我们可以得出这样的结论：电视是人们日常生活中必不可少的工具，因为它可以让我们感到放松，也可以起到陪伴的作用。'
    },
]
